**Binary classification problem**  - Customer Churn Prediction

In [94]:
import numpy as np
import pandas as pd
import tensorflow as tf 

In [95]:
tf.__version__

'2.5.0'

In [96]:
df = pd.read_csv('Churn_Modelling.csv')

In [97]:
df.head(5)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [99]:
df.describe()

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [100]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [101]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [102]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [103]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [104]:
X[:,2] = le.fit_transform(X[:,2])

In [105]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [106]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [107]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [108]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [109]:
X_train.shape

(8000, 12)

In [110]:
X_test.shape

(2000, 12)

In [111]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [112]:
X_train = sc.fit_transform(X_train)
X_text = sc.fit_transform(X_test)

In [113]:
ann = tf.keras.models.Sequential()

In [114]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [115]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [116]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [117]:
ann.compile(optimizer='adam', loss= 'binary_crossentropy', metrics = ['accuracy'])

In [118]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5873 - accuracy: 0.7235
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4739 - accuracy: 0.7981
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4518 - accuracy: 0.8020
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4414 - accuracy: 0.8049
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4325 - accuracy: 0.8083
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4238 - accuracy: 0.8156
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4114 - accuracy: 0.8274
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3909 - accuracy: 0.8414
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3723 - accuracy: 0.8470
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3608 - accura

In [119]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.02088436]], dtype=float32)

In [120]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [121]:
y_tensor = tf.convert_to_tensor(X_test, dtype=tf.int64) 


In [122]:
y_pred = ann.predict(np.asanyarray(X_test).astype(np.int))
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [123]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1595    0]
 [ 405    0]]


0.7975